# Intitializing a Tensor

In [1]:
import torch

In [4]:
# Intialize a Tensor from list

x = torch.tensor([[1,2]])
y = torch.tensor([[1], [2]])

print(x.shape)
print(y.shape)

print(x.dtype)
print(y.dtype)

# Data type of tensor is same when output
x = torch.tensor([False, 1.0, 2])
print(x)    # All are float 

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64
torch.int64
tensor([0., 1., 2.])


In [5]:
# Tensor with 3 rows and 4 columns filled with zeros
torch.zeros((3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
# Tensor with 3 rows and 4 columns filled with ones
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
# Tensor with 3 rows and 4 columns filled with values in range [0, 10)
torch.randint(low = 0, high = 10, size = (3,4))

tensor([[1, 7, 9, 8],
        [5, 3, 0, 8],
        [0, 2, 0, 6]])

In [8]:
# Tensor with 3 rows and 4 columns filled with random numbers between 0 and 1
torch.rand((3,4))

tensor([[0.8651, 0.3626, 0.5315, 0.8180],
        [0.3588, 0.4022, 0.0651, 0.0481],
        [0.6490, 0.6987, 0.1385, 0.6138]])

In [9]:
# Tensor with 3 rows and 4 columns filled with numbers with normal distribution
torch.randn((3,4))

tensor([[-0.5943,  1.0079, -0.3835,  0.9499],
        [-1.1627,  0.6040,  0.9823,  0.7874],
        [-1.3449, -0.9234, -0.1903, -0.8299]])

In [12]:
# Convert numpy array to tensor
import numpy as np

arr = np.array([[1,2,3], [10,20,30]])
tensor = torch.tensor(arr)

print(tensor)

tensor([[ 1,  2,  3],
        [10, 20, 30]], dtype=torch.int32)
