# Operations on Tensors

In [1]:
import torch

In [2]:
# Multiplication

x = torch.tensor([
    [10, 20, 30], 
    [1, 2, 3]
    ])

y = x * 10

print(y)

tensor([[100, 200, 300],
        [ 10,  20,  30]])


In [3]:
# Addition

x = torch.tensor([
    [10, 20, 30], 
    [1, 2, 3]
    ])

y = x.add(10)

print(y)

tensor([[20, 30, 40],
        [11, 12, 13]])


In [12]:
# Reshape using view

y = torch.tensor([1,2,3,4])
print(y.shape)
print(y)
print()

y = y.view(4,1)
print(y.shape)
print(y)

torch.Size([4])
tensor([1, 2, 3, 4])

torch.Size([4, 1])
tensor([[1],
        [2],
        [3],
        [4]])


In [20]:
# Reshape using squeeze 
# We provide axis index that we want to remove and is applicable only when the axis we want to remove has
# only one item in that dimension

x = torch.randn(10, 1, 10)
print(x.shape)

z1 = torch.squeeze(x, 1)
print(z1.shape)

# or

z2 = x.squeeze((1))
print(z2.shape)

torch.Size([10, 1, 10])
torch.Size([10, 10])
torch.Size([10, 10])


In [24]:
# Reshape using unsqueeze

x = torch.randn(10, 10)
print(x.shape)

z1 = x.unsqueeze(0)
print(z1.shape)

torch.Size([10, 10])
torch.Size([1, 10, 10])


In [34]:
# Unsqueeze with None

x = torch.randn(10, 10)
print(x.shape)

z2, z3, z4 = x[None], x[:, None], x[:, :, None]
print(z2.shape, z3.shape, z4.shape)

torch.Size([10, 10])
torch.Size([1, 10, 10]) torch.Size([10, 1, 10]) torch.Size([10, 10, 1])


In [36]:
# Matrix Multiplication

x = torch.tensor([
    [1, 2, 3, 4],
    [10, 20, 30, 40]
])

print(x)
print(y)

print(torch.matmul(x, y))

tensor([[ 1,  2,  3,  4],
        [10, 20, 30, 40]])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[ 30],
        [300]])


In [37]:
# Matrix Multiplication using @

print(x @ y)

tensor([[ 30],
        [300]])


In [39]:
# Concatenate

x = torch.randn(10, 10, 10)
z = torch.cat([x, x], axis = 0)

print("Cat axis: 0")
print(x.shape)
print(z.shape)

z = torch.cat([x, x], axis = 1)

print("\nCat axis: 1")
print(x.shape)
print(z.shape)

Cat axis: 0
torch.Size([10, 10, 10])
torch.Size([20, 10, 10])

Cat axis: 1
torch.Size([10, 10, 10])
torch.Size([10, 20, 10])


In [49]:
# Maximum value in a tensor

x = torch.arange(25).reshape(5, 5)
print(x)
print("\nMax: ", torch.max(x))

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

Max:  tensor(24)


In [47]:
# Max values along rows with their row index (argmax)
m, argmax = x.max(dim=0)
print(m)
print(argmax)

tensor([20, 21, 22, 23, 24])
tensor([4, 4, 4, 4, 4])


In [48]:
# Max values along columns with their columns index (argmax)
m, argmax = x.max(dim=1)
print(m)
print(argmax)

tensor([ 4,  9, 14, 19, 24])
tensor([4, 4, 4, 4, 4])


In [50]:
# Permute Tensor

x = torch.randn(10, 20, 30)
z = x.permute(2,0,1)
print(x.shape)
print(z.shape)

torch.Size([10, 20, 30])
torch.Size([30, 10, 20])


In [52]:
dir(torch.tensor)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [55]:
help(torch.Tensor)

Help on class Tensor in module torch:

class Tensor(torch._C._TensorBase)
 |  Method resolution order:
 |      Tensor
 |      torch._C._TensorBase
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __abs__ = abs(...)
 |  
 |  __array__(self, dtype=None)
 |  
 |  __array_wrap__(self, array)
 |      # Wrap Numpy array again in a suitable tensor when done, to support e.g.
 |      # `numpy.sin(tensor) -> tensor` or `numpy.greater(tensor, 0) -> ByteTensor`
 |  
 |  __contains__(self, element)
 |      Check if `element` is present in tensor
 |      
 |      Arguments:
 |          element (Tensor or scalar): element to be checked
 |              for presence in current tensor"
 |  
 |  __deepcopy__(self, memo)
 |  
 |  __dir__(self)
 |      Default dir() implementation.
 |  
 |  __eq__ = eq(...)
 |  
 |  __floordiv__(self, other)
 |  
 |  __format__(self, format_spec)
 |      Default object formatter.
 |  
 |  __ge__ = ge(...)
 |  
 |  __gt__ = gt(...)
 |  
 |  __hash__(self)
 | 