# Dataset, Dataloader, Batch Size

In [1]:
# Imports

import torch 
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader 

In [2]:
# Inputs and outputs

x = [
    [1,2],
    [3,4],
    [5,6],
    [7,8]
    ]

y =  [
    [3],
    [7],
    [11],
    [15]
]

# Convert to tensor

X = torch.tensor(x).float()
Y = torch.tensor(y).float()

# Device

device = 'cuda' if torch.cuda.is_available() else 'cpu'

X = X.to(device)
Y = Y.to(device)

In [3]:
# Dataset

class MyDataset(Dataset):
    def __init__(self, x, y):
        self.x = torch.tensor(x).float()
        self.y = torch.tensor(y).float()

    def __len__(self):
        return len(self.x)

    def __getitem__(self, index):
        return self.x[index], self.y[index]

# Instance of dataset
ds = MyDataset(X, Y)

# DataLoader
dl = DataLoader(
    ds,
    batch_size = 2,
    shuffle = True
)

C:\Users\hp\anaconda3\envs\myenv\lib\site-packages\ipykernel_launcher.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """
C:\Users\hp\anaconda3\envs\myenv\lib\site-packages\ipykernel_launcher.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


In [7]:
# Fetch batches from dataloader

for x, y in dl:
    print(x, y)

tensor([[5., 6.],
        [1., 2.]], device='cuda:0') tensor([[11.],
        [ 3.]], device='cuda:0')
tensor([[7., 8.],
        [3., 4.]], device='cuda:0') tensor([[15.],
        [ 7.]], device='cuda:0')


In [8]:
# Model Architecture

class MyNeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()

        self.input_to_hidden_layer = nn.Linear(2,8)
        self.hidden_layer_activation = nn.ReLU()
        self.hidden_to_output_layer = nn.Linear(8, 1)

    def forward(self, x):
        x = self.input_to_hidden_layer(x)
        x = self.hidden_layer_activation(x)
        x = self.hidden_to_output_layer(x)
        return x 

In [9]:
mynet = MyNeuralNetwork().to(device)

loss_fn = nn.MSELoss()

optimizer = torch.optim.SGD(mynet.parameters(), lr = 0.001)

In [13]:
# Training Loop

import time 

loss_history = []

start = time.time()

for _ in range(50):
    for data in dl:
        x, y = data 
        optimizer.zero_grad()
        loss_value = loss_fn(mynet(x), y)
        loss_value.backward()
        optimizer.step()
        loss_history.append(loss_value)

end = time.time()

print("Training Time:", end - start)

Training Time: 0.19301509857177734


In [14]:
# Validation

val_x = [[10, 10]]

val_x = torch.tensor(val_x).float().cuda()

mynet(val_x)

tensor([[21.4817]], device='cuda:0', grad_fn=<AddmmBackward>)